import { personalData } from "./../data/page-data";
import SideBar from "./components/SideBar";
import "../styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head />
      <body className="flex flex-col md:flex-row">
        <SideBar data={personalData} />
        <main className="grow-full w-full  md:basis-2/3 p-8 sm:p-16 ml-auto ">
          {children}
        </main>
      </body>
    </html>
  );
}
